### ISSUE TITLE
Parallelization of after-propagation

### ISSUE THREAD

**Issue by jam31118** [jam31118/rigged-qprop#1]
When the laser is off, each equations for each basis are decoupled. The calculation for these equations may easily distributed to multiple processes. Let's see the inside of `wavefunction.propagate()` method and figure out how to implement parallelization.

**Comment by jam31118** [comment]
# Idea
Consider implementing this post-propagation routine as a separate function, because:
- It seems feasible, since the propagation with spherical harmonics without the external field seems really
- Pedagogic for me. It seems to be a good practice.
- Easy to implement parallelization
  - Since it is a separate routine, it is easy to manage each code
  - Easy to call this routine after the external field, with negligible overhead.

# TO DO
- [ ] The result of this subroutine should be compared to the original routines
- [ ] See the formula and/or the corresponding code internal (namely, `wavefunction.propagate()`) of the `qprop` with external field. Derive the decoupled Schrodinger equations from the external-field case's coupled equations with the external field's strength set to zero. It this derivation succeeded, then the coincidence between this new subroutine and the original one become promised.
- [ ] Use `python` to quickly implement this routine. Also consider making this routine as an extension. Both the CPU and GPU version and even with MPI seems possible with almost similar performance.
- [ ] Implement CPU-MPI version, assigning each 1D TDSE into each MPI process.
- [ ] Implement GPU version.
- [ ] Implement multiple GPU version.

**Comment by jam31118** [comment]
Implementing this routine in python with some C (possibly and hopefully also with CUDA) extension may be a one option. Let's check the calculation time for single core for both `qprop` (thus, pure `C++`) and this python routine. Compare this single core times with the CPU-parallelized (and possibly also with GPU) routine.

**Comment by jam31118** [comment]
May be I should modify the end point of the Hamiltonian matrix! It is for matching the boundary condition of the state function at the origin. See [Bauer *et al*, 2017](https://www.degruyter.com/view/product/455151) for further details.

**Comment by jam31118** [comment]
## TODO
- [ ] **[IMPORTANT]** The tsurff data files such as:
  - [ ] `tsurffpsi.raw`
  - [ ] `tsurff-dpsidr.raw`

- [ ] Update also other required files so that after this post-propagation, all the data files are like just as a normal, pure-`qprop` propagation.
  - [ ] `current-wf.bin`
  - [ ] `real-prop-obser.dat`
  - [ ] `real-prop-vecpot.dat`
  - [ ] `real-prop-wf.dat`
  - [ ] `real-prop-yield.dat`

- [ ] Considering updating even the log files that have been generated such as:
  - [ ] `real-prop.log`
  - [ ] `re.log`
  - [ ] (What else?)

**Comment by jam31118** [comment]
# Development Road-map
- [ ] Implement single-core but with working calculation. Also analyze the result and confirm whether the results from `PPP`(#1) are exactly same as `rigged-qprop`.
  - [ ] Save the value of `imagpot` in binary and load it from the python routine so that exactly the same values can be used.

- [ ] Implement MPI-enabled one.
  - [ ] Use mpi4py

- [ ] Boost by C-extension
  - [ ] Implement [matrix-vector multiplication and Gaussian elimination for complex-valued vectors](https://github.com/jam31118/tdse/issues/21) in [`tdse` module](https://github.com/jam31118/tdse).
  - [ ] Start from applying this extension to single process, not MPI.
  - [ ] Apply this C-extended routine in MPI.

**Comment by jam31118** [comment]
Implemented the first working PPP at 4644c99731dc0fe86c82750edc5500f89bbcfe26
