### ISSUE TITLE
install dependency suggestion

### ISSUE THREAD

**Issue by liuqc0419** [jam31118/rigged-qprop#12]
The compiling time for each of the dependency is quite long, I would suggest to split the installation instead of install.sh. Because if one of the installation is failed, you have to recompile and reinstall the others again. The log file of the installation is unnecessary to be saved, anyway you delete them after the installation.

**Comment by jam31118** [comment]
Agree. Current installation script seems quite time-consuming and inconvenient for users. I'll work on it.

**Comment by jam31118** [comment]
# TODO
- [ ] list the required dependencies before installing them and let the user select which dependencies. Default would be `all`.

- [ ] display which dependencies are already installed and which are not.
 - How should it be implemented? How can program detect or at least guess whether a given dependency has been already installed or not.

- [ ] Also, it should be possible to suppress this prompt for the case where the user interaction may not be available but just fully automated procedure is preferred.
 - it may be implemented through command line argument or something.
