### ISSUE TITLE
Let user be able to interrupt program using SIGINT etc.

### ISSUE THREAD

**Issue by jam31118** [jam31118/rigged-qprop#27]
There seems to be a good [reference for explaining SIGINT in c-python extension][sigint-explanation]. Let's refer to this one and try to implement this KeyboardInterrupt signal by user.

[sigint-explanation]:https://github.com/bboe/bryceboe.com/blob/master/content/properly-handling-the-keyboard-interrupt-exception-sigint-within-a-python-c-module.md

**Comment by jam31118** [comment]
# TODO
- [ ] Put [`signal()`][signal] function at each timestep of the propagation to detect [`SIGINT`][SIGINT] if any.
- [ ] Use [sigaction][sigaction] instead of [signal][signal] for portability across different POSIX distribution. Modify the code for propagation accordingly.
- [ ] Don't print (e.g. using `printf`) anything inside of [handler function (of type `sighandler_t`)][signal].

[signal]: http://man7.org/linux/man-pages/man2/signal.2.html
[sigaction]: http://man7.org/linux/man-pages/man2/sigaction.2.html
[SIGINT]: http://man7.org/linux/man-pages/man7/signal.7.htm
