### ISSUE TITLE
The validity of proper `p-min-tsurff` parameter by monitoring probability flux at R

### ISSUE THREAD

**Issue by jam31118** [jam31118/rigged-qprop#60]
The validity of proper `p-min-tsurff` parameter may be estimated or determined by measuring outer probability flux at `R-tsurff` using `tsurffpsi.raw` and `tsurff-dpsidr.raw`.

We may set a threshold value for probability flux and let the program terminate when the probability flux keeps being below this threshold. By using this criteria, instead of determining by setting `p-min-tsurff`, we may get a satisfactorily valid result in a more unconditional manner. 

## TODO
- [ ] let the program terminate when the probability flux keeps being below this threshold
- [ ] At least, this may be a default behavior if the `p-min-tsurff` is not specified.
- [ ] Let the user specify the threshold for probability flux.
