### ISSUE TITLE
Implement common configuration file for shell script that can be sourced

### ISSUE THREAD

**Issue by jam31118** [jam31118/rigged-qprop#64]
Common configuration file for shell scripts seems to be needed. 

Examples of such entries would be 'binary file name of real propagation', which is currently `real-prop` or 'log file name for real propagation', which is currently `re.log`. 

These configuration may be used in scripts which queries some information from `pgrep`, which requires the binary file name of the queried program, or the log file name so that user can see the current state of calculation status such as number of timesteps that has been calculated for `real-prop` or `eval-tsurff`, possibly fetched from each log file by `tail` command.

## TODO
- [ ] Write the common configuration file
- [ ] Let the scripts that make use of this config file should source this file and use the common variable therein.
- [ ] Consider implementing how can every scripts prevent each other from colliding.
